# Generated by Django 4.1.7 on 2023-03-16 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_subcategory_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topics',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces.', regex='^[a-zA-Z ]+$')]),
        ),
    ]
