# Generated by Django 4.1.7 on 2023-03-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_course_course_alter_topic_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=250),
        ),
    ]
